import os, requests, re, json
from bs4 import BeautifulSoup
from datetime import datetime

DATA_FILE = "subsidies_db.json"
SOURCE_URL = "https://j-net21.smrj.go.jp/snavi/articles"

def fetch_and_merge():
    db = []
    if os.path.exists(DATA_FILE):
        try:
            with open(DATA_FILE, "r", encoding="utf-8") as f:
                db = json.load(f)
        except: db = []
    
    try:
        res = requests.get(SOURCE_URL, timeout=20)
        res.encoding = res.apparent_encoding
        soup = BeautifulSoup(res.text, 'html.parser')
        links = soup.find_all('a', href=re.compile(r'/snavi/articles/\d+'))
        
        seen_titles = {item['title'] for item in db}
        new_items = []
        
        for a in links:
            title = a.get_text(strip=True)
            if len(title) > 15 and title not in seen_titles:
                href = a.get('href')
                url = href if href.startswith('http') else "https://j-net21.smrj.go.jp" + href
                new_items.append({
                    "title": title, "link": url, 
                    "date": datetime.now().strftime("%Y-%m-%d")
                })
                seen_titles.add(title)

        updated_db = (new_items + db)[:1000]
        with open(DATA_FILE, "w", encoding="utf-8") as f:
            json.dump(updated_db, f, ensure_ascii=False, indent=2)
        return updated_db
    except: return db

def generate_html(db):
    list_items = ""
    for item in db[:150]:
        list_items += f"""
        <section class="item">
            <time>{item.get('date', '')}</time>
            <h2>{item['title']}</h2>
            <a href="{item['link']}" target="_blank" rel="noopener">ACCESS DATA</a>
        </section>"""

    html_content = f"""<!DOCTYPE html><html lang="ja">
<head>
<meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>SUBSIDY ARCHIVE</title>
<style>
    :root {{ --bg: #ffffff; --text: #000000; --accent: #000000; --dim: #707070; --border: #eeeeee; }}
    body {{ margin: 0; font-family: "Helvetica Neue", Arial, sans-serif; background: var(--bg); color: var(--text); line-height: 1.6; }}
    .container {{ max-width: 800px; margin: 0 auto; padding: 60px 24px; }}
    header {{ border-bottom: 4px solid var(--accent); padding-bottom: 40px; margin-bottom: 60px; }}
    h1 {{ font-size: 2.5rem; font-weight: 900; letter-spacing: -0.05em; margin: 0; }}
    .stats {{ font-size: 0.9rem; font-weight: 600; color: var(--dim); margin-top: 10px; text-transform: uppercase; }}
    .item {{ padding: 32px 0; border-bottom: 1px solid var(--border); transition: 0.2s; }}
    .item:hover {{ border-bottom-color: var(--accent); }}
    time {{ font-size: 0.8rem; font-weight: 700; color: var(--dim); display: block; }}
    h2 {{ font-size: 1.25rem; font-weight: 700; margin: 8px 0 24px 0; letter-spacing: -0.01em; }}
    a {{ display: inline-block; background: var(--accent); color: #fff; text-decoration: none; padding: 12px 32px; font-size: 0.75rem; font-weight: 900; letter-spacing: 0.1em; }}
    footer {{ margin-top: 100px; padding: 40px 0; border-top: 1px solid var(--border); font-size: 0.7rem; color: var(--dim); text-align: center; }}
</style>
</head>
<body>
    <div class="container">
        <header>
            <h1>SUBSIDY<br>ARCHIVE</h1>
            <div class="stats">System Status: Functional / Records: {len(db)} / Location: Japan</div>
        </header>
        <main>{list_items}</main>
        <footer>
            GENERATED BY AUTOMATED INTELLIGENCE SYSTEM / LAST SYNC: {datetime.now().isoformat()}
        </footer>
    </div>
</body></html>"""

    with open("index.html", "w", encoding="utf-8") as f:
        f.write(html_content)

if __name__ == "__main__":
    generate_html(fetch_and_merge())
